trigger:
- master

pool: 
 vmImage: ubuntu-latest
 
steps:
 - script: echo OPA MUNDO.
   displayName: 'Run a one-line script' 
   
 - script: |
 	echo Add other taskst to build, teste..
 	echo See https://aka.ms/yaml
   displayName: 'Run a multi-line script'
